### ISSUE TITLE
[dev] Checklist mise en place

### ISSUE THREAD

**Issue by ymansiaux** [ymansiaux/testmoveissueGLtoGH#18]
_Issue retrieved from another repository_.
_Originally created on: 2023-03-09_
_Originally posted by: Margot Besnard_

## Mise en place de la plateforme de dev
Ce projet sera développé sur dev.thinkr.fr. Il faut anticiper les demandes pour la plateforme de développement de ce projet :
- [ ] Réfléchir à l'infra nécessaire. Faut-il une version spécifique de R ? Une version du CRAN spécifique ? Si oui, contacter Colin dans #bakaverse_sav
- [ ] Réfléchir aux sessions des users qui auront accès à la plateforme. Quels users (les devs, les client.e.s) ? Contacter Antoine dans #bakaverse_sav, pour pouvoir mettre en place la plateforme avec lui.
## Finalisation du board
- [ ] Ajouter les colonnes des issues dans le board dans l'ordre : Bloqué, Prêt, En cours, Révision, A valider. Les autres sont en bonus.
## Calendrier
- [ ] Remplir les Key Dates - _e.g. dates de livraisons intermédiaires, date range des phases du projet_
- [ ] Remplir le calendrier prévisionnel - _utiliser le fichier "dev/lead_dev_manage_calendar.Rmd" section Créneaux .. à intégrer au Wiki du projet_
## Gestion des compte-rendus
- [ ] Choisir la méthode de partage de comptes-rendus (Wiki ou projet séparé) et l'indiquer dans la présentation du projet (= Wiki Home) : https://gitlab.com//example-weekly/-/wikis/home
- [ ] Indiquer aussi la méthode de partage de CR dans l'issue de Bienvenue du Client : NA
## Accès au projet sur Forge
- [ ] Créer un groupe dédié à l'entreprise des clients - _Menu > Groups > Create group_
- [ ] Inviter les clients sur notre GitLab - _Menu > Admin puis dans Users > New user (mettre Projects limit à 0 et décocher Can create group)_
- [ ] Ajouter chaque utilisateur au groupe dédié en tant que "Guest"
- [ ] Ajouter le groupe en tant que "Guest" dans le dépôt créé pour le projet (Ils pourront voir le Kanban, mais pas le code)
- [ ] Notifier chaque utilisateur en les mentionnant dans un commentaire de l'issue : NA avec le texte suivant : 
```
Merci de bien vouloir lire et valider le contenu de cette page.
Si vous lisez ce message dans un email, vous pouvez cliquer sur le lien suivant pour accéder à la page :
NA
[at]mention, [at]mention, ...
```

- [ ] Prévenir les chefs de projets de monter le niveau de Notification à "Watch" sur la page d'acceuil du projet pour recevoir toutes les notifications
